"""bookrequest

Revision ID: db029ba0a453
Revises: 
Create Date: 2020-02-17 01:59:35.129290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db029ba0a453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_request_email'), 'book_request', ['email'], unique=False)
    op.create_index(op.f('ix_book_request_timestamp'), 'book_request', ['timestamp'], unique=False)
    op.create_index(op.f('ix_book_request_title'), 'book_request', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_request_title'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_timestamp'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_email'), table_name='book_request')
    op.drop_table('book_request')
    # ### end Alembic commands ###
